import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Python backend (its venv ships unrelated .ts files)
    "backend-pathway/**",
    // Exported brand-pack assets (generated by a design tool, not app code)
    "public/brand/**",
  ]),
]);

export default eslintConfig;
